### ISSUE TITLE
Cannot upload profile picture and cover photo

### ISSUE THREAD

**Issue by tibonova** [steemit/steemconnect#115]
I've visited [SteemConnect](https://steemconnect.com/profile) and wanted to upload a new profile picture (my account is @tibonova at Steem).

I couldn't upload the picture, the process had stuck.
I couldn't change my info on Steemit either.
I had cleared my profile on SteemConnect, and I was able to change my profile on Steemit.

However, image uploading on SteemConnect still does the same (stuck). 

_OS: Ubuntu 14.04
Browser: Chromium v61.0.3163.100_

**Comment by bonustrack** [comment]
Closing this issue, it's related to SteemConnect v1 which is depreciated and will be closed on 10 march.
