### ISSUE TITLE
link shows 404

### ISSUE THREAD

**Issue by pimato** [steemit/steemconnect#116]
I am on https://steemconnect.com/developers and want to click on the download button for the  

> Steem Connect JavaScript SDK

 but it gives me an : 

`https://raw.githubusercontent.com/adcpm/steemconnect/dev/dist/steemconnect.min.js`

**Comment by bonustrack** [comment]
Closing this issue, it's related to SteemConnect v1 which is depreciated and will be closed on 10 march.
