### ISSUE TITLE
migration plan high level overview

### ISSUE THREAD

**Issue by sneak** [steemit/steemconnect#122]
note: apps are already using steemconnect2 apis, so this transfer must preserve functionality of steemconnect at all times.

1. steemit to decide on new domain registrar
1. steemit to decide on new dns hosting
1. migrate/transfer domain
1. setup steemit dns hosting
1. setup new AWS account to host steemconnect
1. setup postgres RDS
1. setup beanstalk app
1. cycle @steemconnect user keys

**Comment by goldibex** [comment]
Okay. These issues are all documented now in the Migration milestone. This issue is now a tracking issue to be closed when all other issues in the Migration milestone are also closed.
