### ISSUE TITLE
Set up new AWS account to host Steemconnect

### ISSUE THREAD

**Issue by goldibex** [steemit/steemconnect#125]
The new environment will need to be able to deploy a complete instance of steemconnect. @fabien can you please document the requirements here? Database, etc.

**Comment by goldibex** [comment]
And to be clear, this is a complete AWS _account_, not a Beanstalk under an existing one.

**Comment by bonustrack** [comment]
We need a server with:
- Node.js >= 7.7.1 
- And a Postgres database 

There is a Dockerfile is the repo here https://github.com/steemit/steemconnect/blob/dev/Dockerfile

Now we use:
Heroku to host server and db
Domain registrar: ovh.com (steemconnect.com).
DNS: Cloudflare
