### ISSUE TITLE
invalid_grant error

### ISSUE THREAD

**Issue by jlebrijo** [steemit/steemconnect#166]
I am trying to make login with Oauth2:
```
https://v2.steemconnect.com/api/oauth2/authorize?client_id=crowdini.app&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fauth%2Fsteemconnect%2Fcallback%3Freferring_id%3D&response_type=code&scope=vote%2Ccomment&state=5710294e8f887b8ef979d046783ca3fb1b25fd9db5fbfe6b
```

But I am having the following response:
```
{
error: "invalid_grant",
error_description: "The token has invalid role"
}
```

Have you an idea of what am I missing?

Thanks!

**Comment by bonustrack** [comment]
Are you using the SDK https://github.com/steemit/sc2-sdk ? The request `https://v2.steemconnect.com/api/oauth2/authorize?...` can only be done by logged user of steemconnect. You most likely want to send user to `https://v2.steemconnect.com/oauth2/authorize?...` instead.

**Comment by jlebrijo** [comment]
Nope, I am trying to write a Strategy for Rails applitations. Then they would be able to login with Steemconnect. >> https://github.com/omniauth/omniauth-oauth2

`https://v2.steemconnect.com/oauth2/authorize?...` gives me a 404 response. The URL I am using is indicated at steemconnect dashboard `https://v2.steemconnect.com/api/oauth2/authorize?...`.

**Comment by gregory-latinier** [comment]
THe source of 404 responses are often that the redirect_uri isn't an exact match of the redirect uris you have set for your app. Please check your app settings in the dashboard

**Comment by bonustrack** [comment]
@jlebrijo the `redirect_uri` must be exactly same as the one you added in your app example: 
https://v2.steemconnect.com/oauth2/authorize?client_id=crowdini.app&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fauth%2Fsteemconnect%2Fcallback&response_type=code&scope=vote%2Ccomment&state=5710294e8f887b8ef979d046783ca3fb1b25fd9db5fbfe6b

**Comment by jlebrijo** [comment]
Thanks @gregory-latinier !

The correct authorize URL is: `https://v2.steemconnect.com/oauth2/authorize?...`

I think in Docs site is incorrect:

![selection_119](https://user-images.githubusercontent.com/553507/34167037-de96d678-e4e0-11e7-89ef-bcc8de2a6a35.png)
