### ISSUE TITLE
Payload for vote operation

### ISSUE THREAD

**Issue by jlebrijo** [steemit/steemconnect#174]
Hi,

I am making a kind of port of sc2-sdk to ruby, but I am blocked with vote operation.

I send a 'api/broadcast' POST with correct auth headers, but I cannot guess how I should send the payload.

Can you provide me an example of paiload for a broadcast vote api call ?

**Comment by bonustrack** [comment]
Hey @jlebrijo it should look like this: https://github.com/steemit/steemconnect/wiki/OAuth-2#broadcast-a-transaction

**Comment by jlebrijo** [comment]
Thanks @bonustrack !! you saved my day!!
