### ISSUE TITLE
invalid_grant error

### ISSUE THREAD

**Issue by jlebrijo** [steemit/steemconnect#180]
Hi,

we are voting with our users credentials, and for some users we are experiencing this error:

```
401 Unauthorized: {"error":"invalid_grant","error_description":"The token has invalid role"}
```

Can you help how to understand this?

Thanks!

**Comment by Atropix** [comment]
if rep = reaches back to 0 3rd time = PoW 
  rep_minimum= 50 4 ever!
;) <3

**Comment by Atropix** [comment]
+ immediate cheetah shutdown initiated!

**Comment by bonustrack** [comment]
@jlebrijo are you still having this issue? We recently solved an issue that may be related.

**Comment by jlebrijo** [comment]
Yes, this is solved. Thanks.
