### ISSUE TITLE
Allow 3p app to reset client secret

### ISSUE THREAD

**Issue by bobdos** [steemit/steemconnect#185]
Is there a way to reset the client secret key of an app which is created by myself ?

Right now I did not find any button or action to achieve the goal above. There is only a "revoke" button in the edit app page to revoke all users who use the app, but no place for the app creator to reset the client secret key ...

Please help. Many thanks.

**Comment by bonustrack** [comment]
@bobdos Actually there is no way to reset that client secret, we may have a button in future to do that. What's the issue with your current client secret?

**Comment by bobdos** [comment]
Hi, @bonustrack

As our client secret is leak to public at some point, how to fix this problem ?

**Comment by bonustrack** [comment]
@bobdos If this happen you can contact us in discord https://discordapp.com/invite/G95rNZs

**Comment by bonustrack** [comment]
About the implementation here is what we can do:
- Add a button "Reset" on the page app (visible only for app owner):
![image](https://user-images.githubusercontent.com/16245250/39049330-450e24c0-44cb-11e8-85ea-e193e3cb485b.png)
- When the app owner click on it there must be a confirm modal that saying `Are you sure you want to reset your current client secret?`
- When user confirm the modal a request must be send to the server to the route `/api/apps/@client_id/reset-secret`
- This route must be created here `/routes/apps.js` and working similary than edit an app, user is authenticated and client_secret is updated to the related client_id. We need to make that the update sql request select the user as app owner (https://github.com/steemit/steemconnect/blob/master/routes/apps.js#L101-L104)
- The code for generate secret is https://github.com/steemit/steemconnect/blob/master/routes/apps.js#L69

**Comment by bonustrack** [comment]
Closed by #253
