### ISSUE TITLE
Rails Devise integration?

### ISSUE THREAD

**Issue by bitcoiners** [steemit/steemconnect#188]
Hello,
I am developing a Rails app and want to integrate with steemconnect authenticaiton.
Can Devise and Steemconnect work together?

**Comment by inertia186** [comment]
You should be able to use SteemConnect with OmniAuth.  Devise understand OmniAuth as well.  Here's how that's done with twitter as the provider.

http://railscasts.com/episodes/235-devise-and-omniauth-revised

It should be possible to set up a generic provider:

https://github.com/omniauth/omniauth/wiki

I've only fiddle with SteemConnect via OmniAuth a little bit, so I'm not sure about the details of getting it to work in Rails.

**Comment by bitcoiners** [comment]
Is there a generic OmniAuth implementation for SteemConnect?
There should be..

**Comment by bonustrack** [comment]
@bitcoiners is this solving your issue https://rubygems.org/gems/omniauth-steemconnect/versions/0.1.0 ?

**Comment by bitcoiners** [comment]
Yes. Thx.
