### ISSUE TITLE
Allow steemconnect app creator access to his password or key

### ISSUE THREAD

**Issue by gluneau** [steemit/steemconnect#191]
Would want to set account picture and banner. 

And be able to use steem account as any other account.

**Comment by kwlvarun** [comment]
Yes, I agree. I didn't know that I won't be able to login in the app account to update the profile. I am still curious to understand that how STEEM/SBD transfer will happen?

**Comment by bonustrack** [comment]
I'm closing this issue, it's a duplicate of #190
