### ISSUE TITLE
Operation "set_withdraw_vesting_route" is not not working

### ISSUE THREAD

**Issue by etherd** [steemit/steemconnect#208]
I tried redirecting the powerdown SP from one of my accounts to another and entered the correct credentials, but the operation will not work. It gives the "Oops something went wrong" error message and no error log in the browser console.

I tested this on Chrome by using the https://steemconnect.com/sign/set_withdraw_vesting_route?from_account=[from_account]&to_account=[to_account]&percent=10000&auto_vest=false URL.

This does not work for anyone who tries it, hence it isn't an isolated issue.

**Comment by bonustrack** [comment]
It seem that we have the similar problem that what we had with escrow operation. The param `percent` should be an integer but SteemConnect turn it to string:
![image](https://user-images.githubusercontent.com/16245250/39766693-126d1c22-530f-11e8-8c4a-d0a6d9567cce.png)

**Comment by bonustrack** [comment]
I used this link to test https://steemconnect.com/sign/set_withdraw_vesting_route?from_account=siol&to_account=fabien&percent=1&auto_vest=false

**Comment by bonustrack** [comment]
Fixed in #281
