### ISSUE TITLE
Error: signing escrow-transfer transactions via web-interface & SDK

### ISSUE THREAD

**Issue by Sambillingham** [steemit/steemconnect#209]
**Expected Result** - Broadcast 'escrow_transfer' 
**Actual Result** - General Error: 'Oops! Something went wrong!'

After trying many combinations of arguments I've have been unable to use the steemconnect sign function to successfully create a hot signing link (same result using web interface.)The error page has zero insight into what the issue might be.

Taking the following example can anyone spot if I am doing something obviously wrong. The same parameters work with the steem.js equivalent ```escrowtransfer()``` but fail for steemconnect.
via sdk -
```
          let params = {
            from: 'sambillingham',
            to: 'jeffbernst',
            sbd_amount: '0.000 SBD',
            steem_amount: '1.000 STEEM',
            escrow_id: 28760349,
            agent: 'cutemachine',
            fee: '1.000 STEEM',
            ratification_deadline: '2018-03-24T19:08:45',
            escrow_expiration: '2018-04-20T19:08:45',
            json_meta: JSON.stringify({terms: 'test'})
          }

          steemconnect.sign('escrow-transfer', params);

```
Try link as such 
https://steemconnect.com/sign/escrow-transfer?from=seller&to=buyer&agent=agent&escrow_id=28760349&sbd_amount=0.000%20SBD&steem_amount=1.000%20STEEM&fee=1.000%20STEEM&ratification_deadline='2018-03-24T19%3A08%3A45'&escrow_expiration='2018-04-20T19%3A08%3A45'&json_meta='%7B%22terms%22%3A%20%22test%22%7D'

Always returns an error.

thanks.

**Comment by bonustrack** [comment]
Operation worked for the user using Steem.js. https://steemd.com/b/20860579#17fa066e898c8765c0b0d1f19e2965a1235f9a6b

**Comment by Sambillingham** [comment]
hey @bonustrack yes that is the issue. The operation works using steem.js but not with Steemconnect signing. If possible can you please test with Steemconnect SDK or web UI?

**Comment by Sambillingham** [comment]
> Operation worked for the user using Steem.js. https://steemd.com/b/20860579#17fa066e898c8765c0b0d1f19e2965a1235f9a6b visible on this block: https://api.steemjs.com/getBlock?blockNum=20860579

@bonustrack I noticed you edited your comment and added the block data. Can you calrify what you are suggesting here? 

I agree there are no issues with steem.js.

Have you tested a similar transaction using the steemconnect sign function?

**Comment by Sambillingham** [comment]
Thanks for working on #210 so quickly @gregory-latinier. 

my issue is with the escrow_id - ```cause: escrow_transfer.escrow_id = 36071238	 cause: Illegal value: 36071238 (not an integer)``` do you know the correct way to specify the argument for the escrow_id parameter?

**Comment by hernandev** [comment]
also looking into this. thanks

**Comment by bonustrack** [comment]
We need to change `escrow_id` from string to integer when we parse one of these operations: `escrow_transfer`, `escrow_dispute`, `escrow_release` or `escrow_approve`.

**Comment by gregory-latinier** [comment]
This is a little more complicated than that. 
Those operations are not currently parsed and validated like transfer, vote, etc.
I need to create the different operation helpers that's why I'm changing the difficulty to 2

**Comment by bonustrack** [comment]
@Sambillingham we pushed the changes on production can you confirm that everything is working fine by now for you?

**Comment by CodeBull** [comment]
@bonustrack I have just tested all of the functionality and it is working. @Sambillingham created this issue because I requested him to help me with it. I also requested you on Discord. Thank you for all the hard work you and the team have done.

**Comment by Sambillingham** [comment]
@bonustrack Just checked and signing the escrow transaction is now working as expected. Nice work. Thanks for getting this working. Good to close from my perspective. 👊
