### ISSUE TITLE
Can't logout and switch account when using Busy or Utopian

### ISSUE THREAD

**Issue by Hazae41** [steemit/steemconnect#213]
When I disconnect from steemconnect, then click on the login button on Busy or Utopian, I get connected to Account A

For example

I am logged in busy.org with Account A

I disconnect because I want to use Account B

Once disconnected I click on the "login" button on busy.org

But Account A is logged in steemconnect.com, then Account A is automatically choosen in order to use busy.org

Therefore, it is impossible to use Account B

**Comment by tonimese** [comment]
If you can reproduce the issue, please add vodeo or step by step images.

**Comment by gregory-latinier** [comment]
Fixed by #217
