### ISSUE TITLE
Unable to create an app with steemconnect 

### ISSUE THREAD

**Issue by onozasi** [steemit/steemconnect#220]
#### Expected behavior
Users are expected to have at least 3-6 liquid steem to be able to either create a new app on steem blockchain

#### Actual behavior
Currently, it throws back some errors in the console while users are trying to create a new app 

#### How to reproduce
1. Make sure to have at least 6 liquid steem in your wallet
2. Click <a href="https://v2.steemconnect.com/apps/create">here</a> to create an app 
3. fill in the necessary details (e.g, username)
4.  Click on **create account** and 
6. Input username and wif or active key
7. The app/account will not be created returning an error message in the console shown in the screenshot below.
![console.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521984341/hnetptxt8rikexdvhd0e.png)

* Browser: Google Chrome. Version 65.0.3325.181 (Official Build) (64-bit)
* Operating system: Windows 10.

#### Recording
https://youtu.be/RI55Zqex8CE

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@knowledges/unable-to-create-an-app-with-steemconnect">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gregory-latinier** [comment]
Can you retry with the deployment we just made ?
The error you're showing has nothing to do with the impossibility to create an account.
It came from the blockchain config

**Comment by onozasi** [comment]
I think this has been fixed. i am now able to create an app successfully at least for now
