### ISSUE TITLE
When you writing a blog draft block on right show the invalid date.

### ISSUE THREAD

**Issue by pareshUD** [steemit/steemconnect#222]
Please refer the screenshot.

<img width="1195" alt="screen shot 2018-04-04 at 2 39 15 pm" src="https://user-images.githubusercontent.com/8911074/38299285-37524822-3817-11e8-9827-4c154d50ac91.png">

**Comment by gregory-latinier** [comment]
What this has to do with steemconnect ?
It's a busy.org related issue

**Comment by bonustrack** [comment]
Transfered here https://github.com/busyorg/busy/issues/1718
