### ISSUE TITLE
SteemConnect requires App Icon and Redirect URI format check is incorrect

### ISSUE THREAD

**Issue by jm90m** [steemit/steemconnect#224]
![screen shot 2018-04-05 at 11 52 10 pm](https://user-images.githubusercontent.com/5067716/38403106-05cb0b4a-392f-11e8-8a28-3526514d16ce.png)

**Comment by bonustrack** [comment]
This issue has been solved here #227. If there is still an issue with url format using `///` please add another issue @jm90m
