### ISSUE TITLE
Security Issue 

### ISSUE THREAD

**Issue by BartolomeoItaliano** [steemit/steemconnect#232]
Hi,
I'm wondering if solution you provide is safe. 
If I understand it correctly, if user login you store somewhere his private keys and if app want to make transactions you make it on your side and send to the app transaction result. 
Am I right?

Second thing what if someone eavesdrop network (example: internet provider)
Certainly he will never reach the keys, but he don't have to he can use just interface provided by authorized app.

Another question is: Is "Client Secret" another private key which you use to sign transaction you send to steemconnect?

Kind regards

**Comment by gregory-latinier** [comment]
Hi,
This is completely wrong. We do not store private keys on the server. 
You can check the source code is you like. Everything happens in this file: https://github.com/steemit/steemconnect/blob/master/src/components/Auth/Authorize.js
Steemconnect adds posting authority to your account. Here is an example with my account where I added busy.org

![image](https://user-images.githubusercontent.com/13222767/38732849-16b7668c-3f20-11e8-92d7-c84e59cb4516.png)

Here is the transaction: https://steemd.com/tx/98cbd4580ebff5e85a718813f290ecb2d97cd5ae

Adding the authority happens on the client side. Not on the server.

Regarding the client secret, this is used to authenticate your app and get access tokens

Is it clearer ? :)

**Comment by BartolomeoItaliano** [comment]
I'm still not convinced, if I am making transaction from third party app, where the transaction signing process will take place and from what place my key will be taken?

**Comment by bonustrack** [comment]
@BartolomeoItaliano transactions are signed on server side by SteemConnect using the proxy app account. SteemConnect never hold any user key, but instead we ask user to give permission to post on his behalf using proxy app account key. User provide permission to post on his behalf this way we don't require any key from him.

**Comment by BartolomeoItaliano** [comment]
To sign any transaction you need private key. I'm wondering then, where it is stored? It should be only on my computer and nowhere else. I am really concern where it is if you sign transaction on the server? 
Do you send it anywhere through the network?

**Comment by jakipatryk** [comment]
@BartolomeoItaliano Yes, you need a private key to sign transactions, but, as far as I know, your private key (active) is used only locally in your browser to add authority to the proxy account (for example *busy.app*).

On the SteemConnect server, the proxy account keys are stored and they are used to sign transactions on your behalf, so your private keys are safe and not exposed on any server.

**Comment by BartolomeoItaliano** [comment]
What you mean by proxy account key? Maybe i don't now something about this concept. Only private key can sign transaction there is no bypass to do it. If server can post on Steem Blockchain in my name it means server knows my private key and it means the most important blockchain privacy rule had been broken.

**Comment by bonustrack** [comment]
On Steem you can delegate an authority, it can be the posting authority or active or owner. See my account i allow few SC app to post in my name: https://api.steemjs.com/getAccounts?names[]=fabien . This allow an account to do operation for another using his own key and without user the other one key.

**Comment by BartolomeoItaliano** [comment]
You can do the same thing with Steem and sbd sending transactions?

**Comment by bonustrack** [comment]
If you have the active authority of an user yes but SteemConnect only require user to give his posting authority which only allow these methods: https://github.com/steemit/steemconnect/blob/master/config.json#L4-L9

**Comment by BartolomeoItaliano** [comment]
Thank you. I didn't know you can delegate another account to broadcast transactions in your name, it is really important information.
