### ISSUE TITLE
Integrate new design

### ISSUE THREAD

**Issue by bonustrack** [steemit/steemconnect#236]

**Comment by bonustrack** [comment]
@pareshUD can you share the latest design file for SteemConnect platform?

**Comment by bonustrack** [comment]
Where @pareshUD ?

**Comment by bonustrack** [comment]
https://projects.invisionapp.com/share/6FH528ZXARP#/screens this is not the latest design. We need only the interface latest design (menu in left) with all the pages.

**Comment by bonustrack** [comment]
Last design is here https://projects.invisionapp.com/share/XQHKBT3VR45 please @pareshUD go over every comment and do the changes and update invision

**Comment by pareshUD** [comment]
@bonustrack Did you checked the latest designs on invision?

**Comment by bonustrack** [comment]
@pareshUD i made some comments, can you go over it again?
