### ISSUE TITLE
Request login confirmation after revoking token

### ISSUE THREAD

**Issue by Sekhmet** [steemit/steemconnect#237]
I think it makes sense to request login confirmation after user revoked access token for specific application.
Currently if user logouts all what we can do is to revoke access token and delete it from user's browser. However it makes it hard to change accounts because when user navigates to `https://steemconnect.com/oauth2/authorize` page they get redirected right away without a chance to change an account or logout. If users want to change account they have to go to dashboard and logout from SteemConnect entirely.

**Comment by bonustrack** [comment]
This will be solved with #217
