### ISSUE TITLE
Unable to switch account

### ISSUE THREAD

**Issue by itharagaian** [steemit/steemconnect#239]
I am running on ubuntu lts 16.04
I tested this on chromium and firefox : 

1- i log off my main account from busy
2- i log off my main account from dashboard
3- i return to busy, click on connexion and i am back in my main account

I tried to refresh bot steemconnect and busy, won't fix

so I tested further : 

1- log off busy
2- log off steemconnect dashboard
3- log IN with secondary account in dashboard (WORKS)
4- returned to busy, clicked on connexion -> main account appeared again

**Comment by tonimese** [comment]
I guess you need to make the steps above in another order: 2-1-3
- First log off from dashboard
- then log off from busy
-...

**Comment by gregory-latinier** [comment]
Fixed by #217
