### ISSUE TITLE
Users Can't Login - 503 Service Unavailable

### ISSUE THREAD

**Issue by samrg472** [steemit/steemconnect#272]
SteemConnect is returning a 503 service unavailable error. The display page rendered is "Application Error" provided from Heroku services. The request will hang for 30 seconds before this error is returned.

Server request:
```
POST https://v2.steemconnect.com/api/oauth2/token?code=...&client_secret=...
```

I can confirm the code and secret are correct during the login process. When either the code or client_secret is incorrect, the API will correctly return a JSON error stating the role is invalid. Unfortunately, this means users cannot login.

The roles used are: offline, vote
This has been tested with and without IP filters added on the web interface.

**Comment by bonustrack** [comment]
@samrg472 @DSofter this issue seem related to our recent changes about IP filtering https://busy.org/@gregory.latinier/increasing-steemconnect-security I've just reverted it, can you tell me if its working for you now?
