### ISSUE TITLE
"Save" Button in application edit, in the Steemconnect dashboard doesn't work

### ISSUE THREAD

**Issue by puzzledbytheweb** [steemit/steemconnect#278]
Hello!

I am trying to change the redirect URI's regarding my application and when I click the "save button nothing happens. I am not able to test my auth if I can't edit this.

I tried this in Google Chrome and Firefox.

Thanks in advance!

**Comment by puzzledbytheweb** [comment]
It worked, I removed all data and replaced with a new URI. 
I suggest showing a message when this happens? I had two URL's, "http://127.0.0.1:5000/" and "http://localhost:5000/". I clicked, nothing happened and a message would be helpful.

Anyway,
Thanks and sorry if this counts as spam.
Cheers!

**Comment by cutemachine** [comment]
Just leaving a comment here for the future generation :)

You have to fill in the Allowed IPs section of the form. Otherwise, the save button will not work. There is no hint given.

**Comment by gregory-latinier** [comment]
This issue is corrected and will be deployed today
