### ISSUE TITLE
How to update account profile information?

### ISSUE THREAD

**Issue by miikkikiikki** [steemit/steemconnect#327]
Not clear for me, how we can update account profile information with https://v2.steemconnect.com/sign (Profile Update).
If i can write only name of the user, and no input for name, profile image and etc.
Please help

**Comment by bonustrack** [comment]
@miikkikiikki you will need to generate the link yourself or with SC2-SDK lib with the field(s) you want to edit, here is an example: 
https://steemconnect.com/sign/profile-update?name=Fabien&profile_image=https%3A%2F%2Fipfs.busy.org%2Fipfs%2FQmZDi68NdNJGasKF1e8DKx395rZa9fqGRHidSjbnFfkmwG
You can test busy.org profile edit to see how it's supposed to work with more fields.

**Comment by miikkikiikki** [comment]
@bonustrack thank you for answer! I will try.
