### ISSUE TITLE
on open link to login 404 display

### ISSUE THREAD

**Issue by jvleon** [steemit/steemconnect#349]
Im working in a blog, when I got the login link on steemconect display 404
![captura de pantalla 2018-10-12 a la s 13 52 31](https://user-images.githubusercontent.com/28635865/46888422-17500780-ce26-11e8-8c2b-48a3844e4dbd.png)

my code:

```

import sc2 from 'steemconnect'

// init steemconnect
let api = sc2.Initialize({
    app: 'blog-uttab',
    callbackURL: 'http://localhost:8080',
    accessToken: 'access_token',
    scope: ['vote', 'comment'],
});
// get login URL
let link = api.getLoginURL();
console.log(link)
```

that returns this link
https://steemconnect.com/oauth2/authorize?client_id=blog-uttab&redirect_uri=http%3A%2F%2Flocalhost%3A8080&scope=vote,comment

**Comment by bonustrack** [comment]
This is most likely because the callbackURL is not set, you need to set 'http://localhost:8080' as redirect URI on your app setting here: https://steemconnect.com/apps/@blog-uttab/edit

**Comment by jvleon** [comment]
> This is most likely because the callbackURL is not set, you need to set 'http://localhost:8080' as redirect URI on your app setting here: https://steemconnect.com/apps/@blog-uttab/edit

a lot of thanks !

**Comment by bonustrack** [comment]
You can close the issue if it worked for you.
